In [3]:
import numpy as np

# The Basics

In [4]:
# initialize an array
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# get dimension
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# get shape
a.shape

(3,)

In [9]:
b.shape # rows, columns

(2, 3)

In [10]:
# get type
a.dtype

dtype('int32')

In [11]:
# get size
a.itemsize

4

In [12]:
# get total size (itemsize * no. of items)
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc.

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# get a specific element [row,column]
a[1,5]

13

In [15]:
a[1,-1]

14

In [16]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# get a specific column
a[:,2]

array([ 3, 10])

In [18]:
# [start_index:end_index:step_size]
a[0,1:6:2]

array([2, 4, 6])

In [19]:
a[1,5] =20
print(a)

a[:,2]= [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# get a specific element (work outside in)
b[0,1,1]

4

In [22]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [23]:
# all 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# all 1s matrix
np.ones(((4,2,2)), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [26]:
# any other number (shape,value)
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [27]:
# any other number (full_like)
# take a shape that is already there
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# matrix of random numbers
np.random.rand(4,2)

array([[0.22002444, 0.80605981],
       [0.55030109, 0.3229189 ],
       [0.16714657, 0.11383141],
       [0.29782838, 0.73231157]])

In [29]:
#random integer values
np.random.randint(-3,7,size=(3,3))

array([[-2,  3, -1],
       [ 1,  3,  0],
       [-3,  3, -3]])

In [30]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#  repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
output = np.ones((5,5))

z=np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### be careful while copying arrays!!

In [33]:
a = np.array([1,2,3])
b = a
b[0]=100

print(a)
# it changes a also...

[100   2   3]


In [34]:
# to avoid the above thing
a1 = np.array([1,2,3])
b1 = a1.copy()
b1[0]=100

print(a1)

[1 2 3]


##### no change in 'a1' now

# Mathematics

In [35]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [36]:
a + 2

array([3, 4, 5, 6])

In [37]:
a - 2

array([-1,  0,  1,  2])

In [38]:
a * 2

array([2, 4, 6, 8])

In [39]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [41]:
# take sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [42]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [43]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [44]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [45]:
# determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [46]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [47]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.min(stats)

1

In [49]:
np.max(stats)

6

In [50]:
np.max(stats,axis=1) # axis = 1 are columns

array([3, 6])

In [53]:
np.sum(stats,axis=0) # axis = 0 are rows

array([5, 7, 9])

### Reorganizing Arrays

In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after1 = before.reshape((4,2))
print(after1)

after2 = before.reshape((8,1))
print(after2)

after3 = before.reshape((2,2,2))
print(after3)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [62]:
# Horizontally stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 1, 2, 3, 4])

### Miscellaneous

##### Load Data from File

In [66]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

##### Boolean Masking and Advanced Indexing

In [67]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [68]:
# indexes where filedata > 50
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [69]:
## you can index with a list in numpy
# i want index 1,2,8
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [70]:
# axis = 0 checks downwards in a matrix
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [71]:
# axis = 1 checks rows in a matrix
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

In [72]:
((filedata >50) & (filedata <100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [73]:
~((filedata >50) & (filedata <100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])